# Generated by Django 4.2.30 on 2026-06-19 14:25

import charidfield.fields
import cuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='ntf', primary_key=True, serialize=False, unique=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('notification_type', models.CharField(choices=[('invitation', 'Invitation'), ('quota_warning', 'Quota Warning'), ('quota_exceeded', 'Quota Exceeded'), ('billing_receipt', 'Billing Receipt'), ('key_rotation_alert', 'Key Rotation Alert'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_cancelled', 'Subscription Cancelled')], max_length=50)),
                ('subject', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('resend_message_id', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='user.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient_email', 'notification_type'], name='notificatio_recipie_344dc0_idx'), models.Index(fields=['organization', 'created_at'], name='notificatio_organiz_e72ba1_idx')],
            },
        ),
    ]
