# Generated by Django 4.2.30 on 2026-06-05 17:52

import charidfield.fields
import cuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Export',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='exp_', primary_key=True, serialize=False, unique=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], default='csv', max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('row_count', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('file_content', models.BinaryField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='user.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exports',
                'ordering': ['-created_at'],
            },
        ),
    ]
