# Generated by Django 4.2.30 on 2026-07-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikeys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list, help_text='List of IPs / CIDR ranges this key may be used from. Empty means no restriction.'),
        ),
    ]
