# Generated by Django 4.2.30 on 2026-05-31 10:52

import charidfield.fields
import cuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', charidfield.fields.CharIDField(default=cuid.cuid, help_text='cuid-format identifier for this entity.', max_length=40, prefix='usg_', primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('call_count', models.PositiveIntegerField(default=0)),
                ('flushed_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='user.organization')),
            ],
            options={
                'db_table': 'usage_record',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='usage_recor_organiz_7a841f_idx')],
                'unique_together': {('organization', 'date')},
            },
        ),
    ]
