"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

env = environ.Env()
READ_DOT_ENV_FILE = env.bool("DJANGO_READ_DOT_ENV_FILE", True)
if READ_DOT_ENV_FILE:
    # OS environment variables take precedence over variables from .env
    env.read_env(str(BASE_DIR / ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('DJANGO_SECRET_KEY')

# Application definition

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

THIRD_PARTY_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
]

LOCAL_APPS = [
    "apps.user.apps.UserConfig",
    "apps.invitations.apps.InvitationsConfig",
    "apps.apikeys.apps.ApikeysConfig",
    "apps.metering.apps.MeteringConfig"
]

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS + LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "apps.metering.middleware.UsageMeteringMiddleware",
]

ROOT_URLCONF = "config.urls"
WSGI_APPLICATION = "config.wsgi.application"
AUTH_USER_MODEL = "user.User"

APPEND_SLASH = False
APP_CONTEXT_ROOT = 'flowpilot/api'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': env.str('DB_ENGINE'),
        'NAME': env.str('DB_NAME'),
        'USER': env.str('DB_USER'),
        'PASSWORD': env.str('DB_PASSWORD'),
        'HOST': env.str('DB_HOST'),
        'PORT': env.int('DB_DATABASE_PORT'),
    },
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_SERIALIZER": "apps.user.api.serializers.CustomTokenObtainPairSerializer",
}

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "apps.apikeys.authentication.APIKeyAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [],
    "DEFAULT_THROTTLE_RATES": {},
    "EXCEPTION_HANDLER": "apps.utils.core.ErrorHandling.fp_exception_handler",
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ENABLE_SQL_LOGGING = env.bool("ENABLE_SQL_LOGGING", False)
LOG_DIRECTORY = Path(env.str("LOG_DIRECTORY", "logs"))
LOG_DIRECTORY.mkdir(parents=True, exist_ok=True)
INFO_LOG_FILE_SIZE = env.int("INFO_LOG_FILE_SIZE", 15)
INFO_LOG_FILE_ROTATIONS = env.int("INFO_LOG_FILE_ROTATIONS", 5)
ERROR_LOG_FILE_SIZE = env.int("ERROR_LOG_FILE_SIZE", 15)
ERROR_LOG_FILE_ROTATIONS = env.int("ERROR_LOG_FILE_ROTATIONS", 5)
ROTATING_FILE_HANDLER = "logging.handlers.RotatingFileHandler"
DEBUG_LOG_FILE_SIZE = env.int("DEBUG_LOG_FILE_SIZE", 15)
DEBUG_LOG_FILE_ROTATIONS = env.int("DEBUG_LOG_FILE_ROTATIONS", 5)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'slow_queries': {
            '()': 'apps.utils.core.QueryLogger.SlowQueriesFilter',
            # 'callback': lambda record: len(record.name) > 0  # output slow queries only
        },
    },
    'formatters': {
        'default': {
            'format': '[%(asctime)s] [%(levelname)s] [%(pathname)s:%(lineno)d] [%(process)d:%(thread)d]: [%(message)s]'
        }
    },
    'handlers': {
        'sql_logs': {
            'level': 'DEBUG',
            'class': ROTATING_FILE_HANDLER,
            'filename': LOG_DIRECTORY / 'sql.log',
            'maxBytes': DEBUG_LOG_FILE_SIZE * 1024 * 1024,
            'backupCount': DEBUG_LOG_FILE_ROTATIONS,
            'formatter': 'default',
            'filters': ['slow_queries'],
        },
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
            'formatter': 'default',
        },
        'debug_files': {
            'level': 'DEBUG',
            'class': ROTATING_FILE_HANDLER,
            'formatter': 'default',
            'filename': LOG_DIRECTORY / 'debug.log',
            'maxBytes': DEBUG_LOG_FILE_SIZE * 1024 * 1024,
            'backupCount': DEBUG_LOG_FILE_ROTATIONS,
            'mode': 'a',
        },
        'info_files': {
            'level': 'INFO',
            'class': ROTATING_FILE_HANDLER,
            'formatter': 'default',
            'filename': LOG_DIRECTORY / 'info.log',
            'maxBytes': INFO_LOG_FILE_SIZE * 1024 * 1024,
            'backupCount': INFO_LOG_FILE_ROTATIONS,
            'mode': 'a',
        },
        'error_files': {
            'level': 'WARNING',
            'class': ROTATING_FILE_HANDLER,
            'formatter': 'default',
            'filename': LOG_DIRECTORY / 'error.log',
            'maxBytes': ERROR_LOG_FILE_SIZE * 1024 * 1024,
            'backupCount': ERROR_LOG_FILE_ROTATIONS,
            'mode': 'a',
        },
        'request_files': {
            'level': 'DEBUG',
            'class': ROTATING_FILE_HANDLER,
            'formatter': 'default',
            'filename': LOG_DIRECTORY / 'requests.log',
            'maxBytes': DEBUG_LOG_FILE_SIZE * 1024 * 1024,
            'backupCount': DEBUG_LOG_FILE_ROTATIONS,
            'mode': 'a',
        }
    },
    'root': {'level': 'DEBUG', 'handlers': ['console', 'error_files', 'request_files', 'sql_logs']},
    'loggers': {
        'django': {
            'level': 'WARNING',
            'handlers': ['console', 'error_files'],
            'propagate': False,
        },
        'django.server': {
            'level': 'WARNING',
            'handlers': ['console', 'error_files'],
            'propagate': False,
        },
        'django.db.backends': {
            'level': 'DEBUG' if ENABLE_SQL_LOGGING else 'WARNING',
            'handlers': ['sql_logs'],
            'propagate': False,
        },
        'django.security.*': {
            'level': 'WARNING',
            'handlers': ['console', 'error_files'],
            'propagate': False,
        },
        'django.security.csrf': {
            'level': 'WARNING',
            'handlers': ['console', 'error_files'],
            'propagate': False,
        },
    },
}